# UTXO Indexer Configuration
network: "regtest"  # mainnet/testnet/regtest
data_dir: "data/regtest"
shard_count: 2
cpu_cores: 8      # 16核CPU
memory_gb: 32      # 64GB内存
high_perf: true    # 优先性能
api_port: "8080"
zmq_address: "tcp://localhost:28336"  # ZeroMQ连接地址
mempool_clean_start_height: 567   # 内存池清理起始高度，避免从创世区块开始清理
max_tx_per_batch: 1

# Bitcoin RPC Configuration
rpc:
  chain: "btc"
  host: "localhost"
  port: "8332"
  user: "test"
  password: "test"
